'use strict';

/* Services */


// Demonstrate how to register services
// In this case it is a simple value service.
angular.module('myApp.services', [])
	.factory('availabilityFactory', function () {
		return {
			get: function () {
				var mockData = 

[
   {
      "city":{
         "name":"Bednary",
         "street":[
            {
               "number":[
                  "1",
                  "2",
                  "3"
               ]
            }
         ]
      }
   },

   {
      "city":{
         "name":"Łowicz",
         "street":[
            {
               "name":"Chełmońskiego",
               "number":[
                  "1",
                  "2",
                  "3"
               ]
            }
         ]
      }
   },
   {
      "city":{
         "name":"Sochaczew",
         "street":[
            {
               "number":[
                  "1",
                  "2",
                  "3"
               ]
            }
         ]
      }
   },
   {
      "city":{
         "name":"Skierniewice",
         "street":[
            {
               "name":"19-go Lutego",
               "number":[
                  "1",
                  "2",
                  "3",
                  "4",
                  "5",
                  "6",
                  "10",
                  "12"
               ]
            },
            {
               "name":"25-lecia PRL",
               "number":[
                  "4",
                  "8"
               ]
            },
            {
               "name":"Armi Krajowej",
               "number":[
                  "47",
                  "49",
                  "51",
                  "53",
                  "55",
                  "57",
                  "59"
               ]
            },
            {
               "name":"Asnyka",
               "number":[
                  "3",
                  "5",
                  "7",
                  "9",
                  "78",
                  "84"
               ]
            },
            {
               "name":"Buczka",
               "number":[
                  "2",
                  "4",
                  "6",
                  "8",
                  "10"
               ]
            },
            {
               "name":"Iwaszkiewicza",
               "number":[
                  "2",
                  "4",
                  "5",
                  "6",
                  "7",
                  "8",
                  "9",
                  "10",
                  "11",
                  "12",
                  "14",
                  "16"
               ]
            },
            {
               "name":"Kapitana Hali",
               "number":[
                  "1",
                  "2",
                  "4",
                  "6"
               ]
            },
            {
               "name":"Leśmiana",
               "number":[
                  "1",
                  "3"
               ]
            },
            {
               "name":"Mszczonowska",
               "number":[
                  "21",
                  "23",
                  "25",
                  "27",
                  "31"
               ]
            },
            {
               "name":"Norwida",
               "number":[
                  "2",
                  "3",
                  "4",
                  "5",
                  "6",
                  "7",
                  "8",
                  "9",
                  "11",
                  "13"
               ]
            },
            {
               "name":"Orkana",
               "number":[
                  "3",
                  "5",
                  "7",
                  "8",
                  "10",
                  "12"
               ]
            },
            {
               "name":"Pomologiczna",
               "number":[
                  "1",
                  "9",
                  "11"
               ]
            },
            {
               "name":"Prusa",
               "number":[
                  "1",
                  "3",
                  "3",
                  "4",
                  "5",
                  "6",
                  "8",
                  "8a"
               ]
            },
            {
               "name":"Sucharskiego",
               "number":[
                  "1",
                  "2",
                  "3",
                  "4",
                  "5",
                  "6",
                  "7",
                  "8",
                  "9",
                  "10",
                  "11",
                  "13",
                  "14",
                  "15",
                  "16",
                  "18"
               ]
            },
            {
               "name":"Sobieskiego",
               "number":[
                  "5",
                  "7",
                  "7a",
                  "11a",
                  "13",
                  "13a"
               ]
            },
            {
               "name":"Szarych Szeregów",
               "number":"3"
            },
            {
               "name":"Tetmajera",
               "number":[
                  "1",
                  "2",
                  "3",
                  "4",
                  "5",
                  "6"
               ]
            },
            {
               "name":"Wagnera",
               "number":[
                  "1",
                  "4",
                  "6"
               ]
            },
            {
               "name":"Wańkowicza",
               "number":[
                  "1",
                  "2",
                  "3",
                  "4",
                  "5",
                  "6",
                  "8",
                  "10",
                  "11",
                  "12",
                  "14"
               ]
            },
            {
               "name":"Zawadzkiego",
               "number":[
                  "2a",
                  "2b",
                  "2c",
                  "8"
               ]
            }
         ]
      }
   }
];


				return mockData;
				
			},

		};
	}).
	value('version', '0.1');
